mandatoryAccounts:
  - name: Management
    description: The management (primary) account. Do not change the name field for this mandatory account. Note, the account name can be changed using AWS Console or APIs.
    email: aditya+aws-management@atos.net
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: The log archive account
    email: aditya+aws-log-archive@atos.net
    organizationalUnit: PCS
    warm: false
  - name: Audit
    description: The security audit account (also referred to as the audit account)
    email: aditya+aws-audit@atos.net
    organizationalUnit: PCS
    warm: false
  - name: Network
    description: The network account
    email: aditya+aws-network@atos.net
    organizationalUnit: Infrastructure
    warm: false
workloadAccounts:
  - name: Services
    description: The Services account for shared services
    email: aditya+aws-services@atos.net
    organizationalUnit: Infrastructure
    warm: false
  - name: Infrastructure-Tnt0
    description: Infrastructure-Tnt0 account for tenant 0
    email: aditya+aws-infrastructure-tnt0@atos.net
    organizationalUnit: Infrastructure/Tnt0
    warm: false
  - name: Infrastructure-Tnt3
    description: Infrastructure-Tnt3 account for tenant 3
    email: aditya+aws-infrastructure-tnt3@atos.net
    organizationalUnit: Infrastructure/Tnt3
    warm: false
  - name: Infrastructure-Tnt4
    description: Infrastructure-Tnt4 account for tenant 4
    email: aditya+aws-infrastructure-tnt4@atos.net
    organizationalUnit: Infrastructure/Tnt4
    warm: false
accountDefaults:
  region: us-east-1
  enableCloudTrail: true
  enableGuardDuty: true
  enableSecurityHub: true
  enableSingleSignOn: true
